
// This file has been generated by the GUI designer. Do not modify.
namespace ToxSharpGTK
{
	public partial class GtkMainWindow
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.CheckButton checkbutton1;
		private global::Gtk.ScrolledWindow treescroll1;
		private global::Gtk.TreeView treeview1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.ScrolledWindow nodescroll1;
		private global::Gtk.NodeView nodeview1;
		private global::Gtk.Label label1;
		private global::Gtk.Entry entry1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ToxSharpGTK.GtkMainWindow
			this.Events = ((global::Gdk.EventMask)(32770));
			this.Name = "ToxSharpGTK.GtkMainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ToxSharpGTK.GtkMainWindow.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 8;
			this.hbox1.BorderWidth = ((uint)(4));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.WidthRequest = 160;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("checkbutton1");
			this.checkbutton1.Active = true;
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.vbox1.Add (this.checkbutton1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.checkbutton1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.treescroll1 = new global::Gtk.ScrolledWindow ();
			this.treescroll1.Name = "treescroll1";
			this.treescroll1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child treescroll1.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView ();
			this.treeview1.WidthRequest = 80;
			this.treeview1.CanFocus = true;
			this.treeview1.Events = ((global::Gdk.EventMask)(2816));
			this.treeview1.Name = "treeview1";
			this.treeview1.EnableSearch = false;
			this.treeview1.HeadersVisible = false;
			this.treescroll1.Add (this.treeview1);
			this.vbox1.Add (this.treescroll1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.treescroll1]));
			w3.Position = 1;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			this.notebook1.TabPos = ((global::Gtk.PositionType)(3));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.nodescroll1 = new global::Gtk.ScrolledWindow ();
			this.nodescroll1.Name = "nodescroll1";
			this.nodescroll1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.nodescroll1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child nodescroll1.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView ();
			this.nodeview1.WidthRequest = 256;
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.nodeview1.HeadersVisible = false;
			this.nodescroll1.Add (this.nodeview1);
			this.notebook1.Add (this.nodescroll1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Main");
			this.notebook1.SetTabLabel (this.nodescroll1, this.label1);
			this.label1.ShowAll ();
			this.vbox2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.notebook1]));
			w7.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.vbox2.Add (this.entry1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.entry1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w9.Position = 1;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 532;
			this.DefaultHeight = 399;
			this.Show ();
		}
	}
}
